//! Pivot's type system: the column types the planner understands, plus
//! conversions to and from DuckDB's [`LogicalTypeId`] and parsing of constant
//! values into arrow [`Scalar`]s.
//!
//! The supported [`Type`] set is deliberately small — it mirrors what the
//! executor ([`dispatch`]) currently knows how to build columns for. If
//! DuckDB hands us a logical type outside this set, [`type_from_logical`]
//! returns [`Error::UnsupportedLogicalType`] and short-circuits the rest of
//! plan conversion, so unsupported shapes never reach
//! [`compile`](crate::compile).
//!
//! The `Type <-> LogicalTypeId` mapping is generated by the
//! `type_conversions!` macro from a single list of pairs, so adding a new
//! type is one entry instead of two near-identical match arms.

use arrow_array::cast::AsArray;
use arrow_array::{
    ArrayRef, BooleanArray, Float64Array, Int8Array, Int16Array, Int32Array, Int64Array, Scalar,
    StringViewArray,
};
use duckdb_planner::ScalarValue;
use duckdb_planner::duckdb_bridge::duckdb_types::LogicalTypeId;
use std::fmt;
use std::sync::Arc;
use thiserror::Error;

/// A column type Pivot can plan and execute against.
///
/// Each variant maps 1-1 to an arrow array kind in the executor, and
/// bidirectionally to a [`LogicalTypeId`] in DuckDB via the
/// `type_conversions!` macro below.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Type {
    Boolean,
    Int8,
    Int16,
    Int32,
    Int64,
    /// DuckDB `HUGEINT` — the result type of `SUM` over integers. Pivot's
    /// executor emits `SUM` as a `Decimal128(38, 0)` column matching this
    /// width, so large sums (e.g. `SUM(user_id)`) stay exact.
    Int128,
    /// DuckDB `DOUBLE` — the result type of `AVG`.
    Float64,
    /// DuckDB `DECIMAL` — the result type of integer division (`AVG` lowers to
    /// `sum / count`, whose `/` yields DECIMAL). Pivot computes it as `Float64`,
    /// so this only needs to round-trip through plan translation.
    Decimal,
    Utf8,
    /// DuckDB `DATE` — days since the epoch. The source parquet stores it as a
    /// small integer (days), so the executor sees an integer column; the type
    /// exists so `DATE` columns/constants survive plan translation and compare.
    Date,
    /// DuckDB `TIMESTAMP` — the type of a timestamp column and the result of
    /// `date_trunc`. The source parquet stores it as packed epoch *seconds* in
    /// an `Int64` column, so the executor treats it as `Int64` seconds.
    Timestamp,
}

impl fmt::Display for Type {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let name = match self {
            Type::Boolean => "Boolean",
            Type::Int8 => "Int8",
            Type::Int16 => "Int16",
            Type::Int32 => "Int32",
            Type::Int64 => "Int64",
            Type::Int128 => "Int128",
            Type::Float64 => "Float64",
            Type::Decimal => "Decimal",
            Type::Utf8 => "Utf8",
            Type::Date => "Date",
            Type::Timestamp => "Timestamp",
        };
        f.write_str(name)
    }
}

#[derive(Error, Debug)]
pub enum Error {
    #[error("Unsupported logical type: {0:?}")]
    UnsupportedLogicalType(LogicalTypeId),
    #[error("Unsupported scalar type: {0:?}")]
    UnsupportedScalarType(Type),
    #[error("Invalid scalar value '{raw_value}' for logical type {logical_type:?}: {reason}")]
    InvalidScalarValue {
        logical_type: LogicalTypeId,
        raw_value: String,
        reason: String,
    },
}

/// Generates a pair of conversion functions between Pivot's [`Type`] and
/// DuckDB's [`LogicalTypeId`] from a single list of pairs, so the mapping
/// is defined once and both directions stay in sync.
///
/// - `type_from_logical`: DuckDB `LogicalTypeId` -> Pivot `Type` (fallible,
///   returns `Err` for unmapped DuckDB types).
/// - `logical_from_type`: Pivot `Type` -> DuckDB `LogicalTypeId` (infallible,
///   every Pivot type has a DuckDB counterpart).
macro_rules! type_conversions {
    ( $( ($pivot:path, $duckdb:path) ),+ $(,)? ) => {
        pub fn type_from_logical(duckdb_type: LogicalTypeId) -> Result<Type, Error> {
            match duckdb_type {
                $( $duckdb => Ok($pivot), )+
                _ => Err(Error::UnsupportedLogicalType(duckdb_type)),
            }
        }

        pub fn logical_from_type(pivot_type: &Type) -> LogicalTypeId {
            match pivot_type {
                $( $pivot => $duckdb, )+
            }
        }
    };
}

type_conversions! {
    (Type::Boolean,   LogicalTypeId::BOOLEAN),
    (Type::Int8,      LogicalTypeId::TINYINT),
    (Type::Int16,     LogicalTypeId::SMALLINT),
    (Type::Int32,     LogicalTypeId::INTEGER),
    (Type::Int64,     LogicalTypeId::BIGINT),
    (Type::Int128,    LogicalTypeId::HUGEINT),
    (Type::Float64,   LogicalTypeId::DOUBLE),
    (Type::Decimal,   LogicalTypeId::DECIMAL),
    (Type::Utf8,      LogicalTypeId::VARCHAR),
    (Type::Date,      LogicalTypeId::DATE),
    (Type::Timestamp, LogicalTypeId::TIMESTAMP),
}

/// Parse a DuckDB [`ScalarValue`] (logical type + raw string) into an arrow
/// [`Scalar<ArrayRef>`] suitable for use as a constant in the executor.
pub fn build_scalar_value(
    ScalarValue {
        logical_type,
        raw_value,
    }: ScalarValue,
) -> Result<Scalar<ArrayRef>, Error> {
    let pivot_type = type_from_logical(logical_type.clone())?;
    let array: ArrayRef = match pivot_type {
        Type::Boolean => Arc::new(
            BooleanArray::new_scalar(parse_scalar::<bool>(&raw_value, logical_type.clone())?)
                .into_inner(),
        ),
        Type::Int8 => Arc::new(
            Int8Array::new_scalar(parse_scalar::<i8>(&raw_value, logical_type.clone())?)
                .into_inner(),
        ),
        Type::Int16 => Arc::new(
            Int16Array::new_scalar(parse_scalar::<i16>(&raw_value, logical_type.clone())?)
                .into_inner(),
        ),
        Type::Int32 => Arc::new(
            Int32Array::new_scalar(parse_scalar::<i32>(&raw_value, logical_type.clone())?)
                .into_inner(),
        ),
        Type::Int64 => Arc::new(
            Int64Array::new_scalar(parse_scalar::<i64>(&raw_value, logical_type.clone())?)
                .into_inner(),
        ),
        Type::Float64 => Arc::new(
            Float64Array::new_scalar(parse_scalar::<f64>(&raw_value, logical_type.clone())?)
                .into_inner(),
        ),
        Type::Utf8 => Arc::new(StringViewArray::new_scalar(raw_value).into_inner()),
        // DuckDB serialises a DATE constant as "YYYY-MM-DD"; let arrow parse it
        // to a Date32 (days since epoch). Comparisons coerce both sides to a
        // common numeric type, so this lines up with the integer day-count the
        // parquet stores for a `DATE` column.
        Type::Date => {
            let strs = arrow_array::StringArray::from(vec![raw_value.clone()]);
            let casted =
                arrow::compute::cast(&strs, &arrow_schema::DataType::Date32).map_err(|err| {
                    Error::InvalidScalarValue {
                        logical_type: logical_type.clone(),
                        raw_value: raw_value.clone(),
                        reason: err.to_string(),
                    }
                })?;
            let days = casted
                .as_primitive::<arrow_array::types::Date32Type>()
                .value(0);
            Arc::new(arrow_array::Date32Array::new_scalar(days).into_inner())
        }
        // SUM result types and TIMESTAMP never appear as query *constants*
        // (TIMESTAMP shows up only as a column / date_trunc result), so we don't
        // need to materialise them as scalar literals.
        Type::Int128 | Type::Decimal | Type::Timestamp => {
            return Err(Error::UnsupportedScalarType(pivot_type));
        }
    };

    Ok(Scalar::new(array))
}

fn parse_scalar<T>(raw_value: &str, logical_type: LogicalTypeId) -> Result<T, Error>
where
    T: std::str::FromStr,
    T::Err: std::fmt::Display,
{
    raw_value
        .parse::<T>()
        .map_err(|err| Error::InvalidScalarValue {
            logical_type,
            raw_value: raw_value.to_string(),
            reason: err.to_string(),
        })
}
