//! Pivot's type system: the column types the planner understands, plus
//! conversions to and from DuckDB's [`LogicalTypeId`] and parsing of constant
//! values into arrow [`Scalar`]s.
//!
//! The supported [`Type`] set is deliberately small — it mirrors what the
//! executor ([`dispatch`]) currently knows how to build columns for. If
//! DuckDB hands us a logical type outside this set, [`type_from_logical`]
//! returns [`Error::UnsupportedLogicalType`] and short-circuits the rest of
//! plan conversion, so unsupported shapes never reach
//! [`compile`](crate::compile).
//!
//! The `Type <-> LogicalTypeId` mapping is generated by the
//! `type_conversions!` macro from a single list of pairs, so adding a new
//! type is one entry instead of two near-identical match arms.

use arrow_array::{
    ArrayRef, BooleanArray, Float32Array, Float64Array, Int8Array, Int16Array, Int32Array,
    Int64Array, Scalar, StringViewArray, UInt8Array, UInt16Array, UInt32Array, UInt64Array,
};
use arrow_schema::{DataType, TimeUnit};
use duckdb_planner::ScalarValue;
use duckdb_planner::duckdb_bridge::duckdb_types::LogicalTypeId;
use std::fmt;
use std::sync::Arc;
use thiserror::Error;

/// A column type Pivot can plan and execute against.
///
/// Each variant maps 1-1 to an arrow array kind in the executor, and
/// bidirectionally to a [`LogicalTypeId`] in DuckDB via the
/// `type_conversions!` macro below.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Type {
    Boolean,
    Int8,
    Int16,
    Int32,
    Int64,
    UInt8,
    UInt16,
    UInt32,
    UInt64,
    /// DuckDB `HUGEINT` — the result type of `SUM` over integers. Pivot's
    /// executor emits `SUM` as a `Decimal128(38, 0)` column matching this
    /// width, so large sums (e.g. `SUM(user_id)`) stay exact.
    Int128,
    /// DuckDB `REAL`/`FLOAT` — a single-precision float column.
    Float32,
    /// DuckDB `DOUBLE` — a double-precision float column and the result type of `AVG`.
    Float64,
    /// DuckDB `DECIMAL` — the result type of integer division (`AVG` lowers to
    /// `sum / count`, whose `/` yields DECIMAL). Pivot computes it as `Float64`,
    /// so this only needs to round-trip through plan translation.
    Decimal,
    Utf8,
    /// DuckDB `DATE` — days since the epoch. The source parquet stores it as a
    /// small integer (days), so the executor sees an integer column; the type
    /// exists so `DATE` columns/constants survive plan translation and compare.
    Date,
    /// DuckDB `TIMESTAMP` — the type of a timestamp column and the result of
    /// `date_trunc`. The source parquet stores it as packed epoch *seconds* in
    /// an `Int64` column, so the executor treats it as `Int64` seconds.
    Timestamp,
}

impl fmt::Display for Type {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let name = match self {
            Type::Boolean => "Boolean",
            Type::Int8 => "Int8",
            Type::Int16 => "Int16",
            Type::Int32 => "Int32",
            Type::Int64 => "Int64",
            Type::UInt8 => "UInt8",
            Type::UInt16 => "UInt16",
            Type::UInt32 => "UInt32",
            Type::UInt64 => "UInt64",
            Type::Int128 => "Int128",
            Type::Float32 => "Float32",
            Type::Float64 => "Float64",
            Type::Decimal => "Decimal",
            Type::Utf8 => "Utf8",
            Type::Date => "Date",
            Type::Timestamp => "Timestamp",
        };
        f.write_str(name)
    }
}

#[derive(Error, Debug)]
pub enum Error {
    #[error("Unsupported logical type: {0:?}")]
    UnsupportedLogicalType(LogicalTypeId),
    #[error("Unsupported scalar constant: {0}")]
    UnsupportedScalarConstant(ScalarValue),
}

/// Generates the conversion functions between Pivot's [`Type`], DuckDB's
/// [`LogicalTypeId`], and the executor's physical arrow [`DataType`] from a
/// single table of triples, so every type is described in one place and the
/// directions can't drift.
///
/// Each row is `(pivot Type, DuckDB LogicalTypeId, physical arrow DataType)`:
///
/// - `type_from_logical`: DuckDB `LogicalTypeId` -> Pivot `Type` (fallible,
///   returns `Err` for unmapped DuckDB types).
/// - `logical_from_type`: Pivot `Type` -> DuckDB `LogicalTypeId` (infallible,
///   every Pivot type has a DuckDB counterpart).
/// - `physical_arrow_type`: Pivot `Type` -> the arrow `DataType` a column of that
///   type carries (infallible).
///
/// The arrow column is where the "logical vs physical" facts live, once:
/// `Date` is `Date32`, `Timestamp` is `Timestamp(Second)`, and the wide aggregate
/// types (`Int128`/`Decimal`) land on `Decimal128(38, 0)`/`Float64`. This is the
/// single arrow type a value carries everywhere; only the group-by drops a
/// temporal column to its backing int (`temporal_to_int`) to hash/encode it,
/// restoring the type on its output.
macro_rules! type_conversions {
    ( $( ($pivot:path, $duckdb:path, $arrow:expr) ),+ $(,)? ) => {
        pub fn type_from_logical(duckdb_type: LogicalTypeId) -> Result<Type, Error> {
            match duckdb_type {
                $( $duckdb => Ok($pivot), )+
                _ => Err(Error::UnsupportedLogicalType(duckdb_type)),
            }
        }

        pub fn logical_from_type(pivot_type: &Type) -> LogicalTypeId {
            match pivot_type {
                $( $pivot => $duckdb, )+
            }
        }

        /// The arrow [`DataType`] a column of this `Type` carries.
        ///
        /// Note this is many-to-one (`Decimal` and `Float64` both map to
        /// `Float64`), so it has no clean inverse: recovering the logical type
        /// from an arrow column is exactly the ambiguity the rest of the planner
        /// carries the [`Type`] around to avoid.
        pub fn physical_arrow_type(pivot_type: &Type) -> DataType {
            match pivot_type {
                $( $pivot => $arrow, )+
            }
        }
    };
}

type_conversions! {
    (Type::Boolean,   LogicalTypeId::BOOLEAN,   DataType::Boolean),
    (Type::Int8,      LogicalTypeId::TINYINT,   DataType::Int8),
    (Type::Int16,     LogicalTypeId::SMALLINT,  DataType::Int16),
    (Type::Int32,     LogicalTypeId::INTEGER,   DataType::Int32),
    (Type::Int64,     LogicalTypeId::BIGINT,    DataType::Int64),
    (Type::UInt8,     LogicalTypeId::UTINYINT,  DataType::UInt8),
    (Type::UInt16,    LogicalTypeId::USMALLINT, DataType::UInt16),
    (Type::UInt32,    LogicalTypeId::UINTEGER,  DataType::UInt32),
    (Type::UInt64,    LogicalTypeId::UBIGINT,   DataType::UInt64),
    (Type::Int128,    LogicalTypeId::HUGEINT,   DataType::Decimal128(38, 0)),
    (Type::Float32,   LogicalTypeId::FLOAT,     DataType::Float32),
    (Type::Float64,   LogicalTypeId::DOUBLE,    DataType::Float64),
    (Type::Decimal,   LogicalTypeId::DECIMAL,   DataType::Float64),
    (Type::Utf8,      LogicalTypeId::VARCHAR,   DataType::Utf8View),
    (Type::Date,      LogicalTypeId::DATE,      DataType::Date32),
    (Type::Timestamp, LogicalTypeId::TIMESTAMP, DataType::Timestamp(TimeUnit::Second, None)),
}

/// Convert a typed DuckDB [`ScalarValue`] into an arrow [`Scalar<ArrayRef>`]
/// suitable for use as a constant in the executor.
pub fn build_scalar_value(value: ScalarValue) -> Result<Scalar<ArrayRef>, Error> {
    let array: ArrayRef = match value {
        ScalarValue::Boolean(v) => Arc::new(BooleanArray::new_scalar(v).into_inner()),
        ScalarValue::Int8(v) => Arc::new(Int8Array::new_scalar(v).into_inner()),
        ScalarValue::Int16(v) => Arc::new(Int16Array::new_scalar(v).into_inner()),
        ScalarValue::Int32(v) => Arc::new(Int32Array::new_scalar(v).into_inner()),
        ScalarValue::Int64(v) => Arc::new(Int64Array::new_scalar(v).into_inner()),
        ScalarValue::UInt8(v) => Arc::new(UInt8Array::new_scalar(v).into_inner()),
        ScalarValue::UInt16(v) => Arc::new(UInt16Array::new_scalar(v).into_inner()),
        ScalarValue::UInt32(v) => Arc::new(UInt32Array::new_scalar(v).into_inner()),
        ScalarValue::UInt64(v) => Arc::new(UInt64Array::new_scalar(v).into_inner()),
        ScalarValue::Float32(v) => Arc::new(Float32Array::new_scalar(v).into_inner()),
        ScalarValue::Float64(v) => Arc::new(Float64Array::new_scalar(v).into_inner()),
        ScalarValue::Utf8(v) => Arc::new(StringViewArray::new_scalar(v).into_inner()),
        // DuckDB's DATE is days since the epoch, the same as arrow `Date32`.
        // Comparisons coerce both sides to a common numeric type, so this lines up
        // with the integer day-count the parquet stores for a `DATE` column.
        ScalarValue::Date(days) => {
            Arc::new(arrow_array::Date32Array::new_scalar(days).into_inner())
        }
        // SUM/AVG result types, TIMESTAMP, INTERVAL, and types the bridge doesn't
        // decode never appear as query *constants* we materialise (TIMESTAMP shows
        // up only as a column/date_trunc result; INTERVAL is consumed by interval
        // arithmetic; HUGEINT/DECIMAL constants aren't supported).
        other => return Err(Error::UnsupportedScalarConstant(other)),
    };

    Ok(Scalar::new(array))
}
