#!/bin/sh

set -e

case "${1:-}" in
    remove|deconfigure)
        if [ -d /run/systemd/system ]; then
            deb-systemd-invoke stop pivot.service >/dev/null || true
        fi
        ;;
esac
