[package]
name = "metastore-yaml"
version.workspace = true
edition.workspace = true
description = "YAML-backed metastore provider for PivotDB."

[dependencies]
metastore = { workspace = true }
catalog = { workspace = true }
datastore-delta = { workspace = true }
dispatch = { workspace = true }

serde = { workspace = true }
thiserror = { workspace = true }
serde_yaml_ng = { workspace = true }

[dev-dependencies]
base64 = { workspace = true }
