[package]
name = "benchmarks"
version.workspace = true
edition.workspace = true

[dependencies]
server = { workspace = true }
catalog = { workspace = true }
planner = { workspace = true }
dispatch = { workspace = true }

clap = { workspace = true, features = ["env"] }
tokio = { workspace = true, features = ["rt-multi-thread", "net", "macros", "sync"] }
tokio-postgres = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ureq = { workspace = true }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
core_affinity = { workspace = true }
sysinfo = { workspace = true }

[[bin]]
name = "pivot-bench"
path = "src/main.rs"
