//! `pivot-cli`: a local pivotdb session in one command.
//!
//! Running the binary starts the engine in-process and opens the built-in
//! interactive shell straight onto it: statements run through the embedded
//! [`session::Session`], so nothing listens anywhere and nothing external is
//! required. Table data lives in a private temporary directory removed when
//! the session ends (`--path` keeps it), alongside a generated `pivot.yaml`
//! that also works verbatim as a `pivotdb-server --config` file. When stdin is
//! not a terminal, statements are read from it instead of a prompt, so
//! `pivot-cli < script.sql` runs a script.

mod render;
mod repl;
mod sql_split;

use std::io::IsTerminal;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::ExitCode;
use std::sync::Arc;

use catalog::PivotCatalog;
use clap::Parser;
use datastore_delta::DEFAULT_REFRESH_INTERVAL;
use dispatch::{BUFFER_SIZE, Dispatch};
use metastore::Metastore;
use metastore_disk::{ByteSize, DiskMetastore, MetastoreConfig};

/// The one datastore's name, and the name in the shell's prompt.
const DATASTORE_NAME: &str = "pivot";

/// Share of the machine's memory the buffer pool takes when `--memory` is not
/// given. Half, not the server's 80%: a local session shares the machine with
/// whatever the user is really working on.
const DEFAULT_MEMORY_PCT: usize = 50;

/// An ephemeral local pivotdb session: starts the engine in-process on a
/// temporary directory and opens an interactive SQL shell on it.
#[derive(Parser, Debug)]
#[command(name = "pivot-cli", about, version)]
struct Args {
    /// Keep table data in this directory (created if missing) instead of a
    /// temporary one removed when the session ends.
    #[arg(long, value_name = "DIR")]
    path: Option<PathBuf>,

    /// Memory budget for the buffer pool, such as `8g`. Defaults to half the
    /// machine's memory (PIVOT_MEMORY_PCT overrides the percentage).
    #[arg(long, value_name = "SIZE")]
    memory: Option<ByteSize>,

    /// Number of dispatch worker threads. Defaults to the machine's core count.
    #[arg(long, value_name = "N")]
    workers: Option<usize>,
}

#[derive(Debug, thiserror::Error)]
enum Error {
    #[error(transparent)]
    Io(#[from] std::io::Error),
    #[error("parsing the generated session config: {0}")]
    ParseConfig(#[from] serde_yaml_ng::Error),
    #[error("invalid generated metastore config: {0}")]
    Metastore(#[from] Box<metastore_disk::Error>),
    #[error("failed to open the session datastore: {0}")]
    OpenDatastores(#[source] metastore::Error),
    #[error(transparent)]
    Catalog(#[from] catalog::Error),
    #[error(transparent)]
    Readline(#[from] rustyline::error::ReadlineError),
    #[error("task panicked: {0}")]
    TaskPanicked(#[from] tokio::task::JoinError),
}

type Result<T, E = Error> = std::result::Result<T, E>;

/// Log to stderr, quietly (`warn`) by default: stdout belongs to query
/// results, and the engine's per-query info logging would talk over the
/// interactive session. `RUST_LOG` overrides as usual.
fn init_tracing() {
    let filter = tracing_subscriber::EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("warn"));
    tracing_subscriber::fmt()
        .with_env_filter(filter)
        .with_writer(std::io::stderr)
        .init();
}

/// The generated file, read back: only its `metastore` section, which is all a
/// session needs (the file's optional `server` section means something only to
/// `pivotdb-server`).
#[derive(serde::Deserialize)]
#[serde(deny_unknown_fields)]
struct SessionConfig {
    metastore: MetastoreConfig,
}

/// Write the session's config file: the same format `pivotdb-server --config`
/// reads (the `server` section is optional there, so this file works verbatim
/// with the server too), with one local delta datastore and no `users` section,
/// which selects the built-in trusted `pivot` user.
fn write_session_config(config_path: &Path, data_dir: &Path) -> std::io::Result<()> {
    // A path is an arbitrary string to YAML; double-quote it and escape the
    // two characters that mean something inside a double-quoted scalar.
    let location = data_dir
        .display()
        .to_string()
        .replace('\\', "\\\\")
        .replace('"', "\\\"");
    let text = format!(
        "# Generated by the pivot CLI for this session.\n\
         metastore:\n\
         \x20 datastores:\n\
         \x20   {DATASTORE_NAME}:\n\
         \x20     kind: delta\n\
         \x20     location: \"{location}\"\n\
         \x20     default: true\n"
    );
    std::fs::write(config_path, text)
}

fn run() -> Result<ExitCode> {
    init_tracing();
    let args = Args::parse();

    session::raise_open_file_limit();

    let rt = tokio::runtime::Builder::new_multi_thread()
        .worker_threads(2)
        .enable_all()
        .build()?;
    let code = rt.block_on(run_session(args));
    // A terminating signal can leave the shell's readline call parked on a
    // blocking thread; a plain drop of the runtime would wait for it forever.
    rt.shutdown_background();
    code
}

async fn run_session(args: Args) -> Result<ExitCode> {
    // Signal handling comes first: with handlers installed, no signal can kill
    // the process with its default disposition, so from here on every exit path
    // runs the session directory's cleanup. Ctrl-C cancels the running query
    // (or clears the prompt line); SIGTERM and SIGHUP end the session.
    use tokio::signal::unix::{SignalKind, signal};
    let mut sigint = signal(SignalKind::interrupt())?;
    let mut sigterm = signal(SignalKind::terminate())?;
    let mut sighup = signal(SignalKind::hangup())?;

    // The session directory holds the generated config and, without `--path`,
    // the table data; 0700 keeps both private to this user.
    let session_dir = tempfile::Builder::new()
        .prefix("pivot-")
        .permissions(std::fs::Permissions::from_mode(0o700))
        .tempdir()?;
    let data_dir = match &args.path {
        Some(dir) => {
            std::fs::create_dir_all(dir)?;
            dir.clone()
        }
        None => {
            let dir = session_dir.path().join("data");
            std::fs::create_dir(&dir)?;
            dir
        }
    };

    // Pre-faulting the buffer pool takes seconds on a large machine, so keep
    // signals live while it runs: an interrupt here ends the session before it
    // started, with the directory cleaned up.
    let workers = args.workers.unwrap_or_else(dispatch::default_worker_count);
    let pool_bytes = session::bootstrap::compute_pool_bytes(args.memory, DEFAULT_MEMORY_PCT);
    let dispatch = tokio::select! {
        dispatch = tokio::task::spawn_blocking(move || {
            Dispatch::spin_up(workers, pool_bytes / BUFFER_SIZE, None)
        }) => dispatch?,
        _ = async { tokio::select! {
            _ = sigint.recv() => (), _ = sigterm.recv() => (), _ = sighup.recv() => (),
        }} => {
            eprintln!("interrupted before the session started");
            return Ok(ExitCode::FAILURE);
        }
    };

    // The engine is torn apart here rather than handed to a server: the
    // dispatcher runs the shell's statements, and the worker handles plus the
    // shared exit flag drive shutdown at the end of the session.
    let dispatcher = dispatch.dispatcher().clone();
    let (worker_handles, engine_shutdown) = dispatch.into_parts();

    // The session runs on a generated config file, read back through the same
    // parser and metastore the server uses, so this path cannot drift from a
    // real deployment's. The file stays in the session directory for the user
    // to inspect or reuse.
    let config_path = session_dir.path().join("pivot.yaml");
    write_session_config(&config_path, &data_dir)?;
    let config: SessionConfig = serde_yaml_ng::from_str(&std::fs::read_to_string(&config_path)?)?;
    let metastore: Arc<dyn Metastore> = Arc::new(
        DiskMetastore::open(config.metastore, None, DEFAULT_REFRESH_INTERVAL).map_err(Box::new)?,
    );

    // Open the datastore inside the runtime: it may spawn onto it.
    let datastores = metastore
        .open_datastores(&dispatcher)
        .map_err(Error::OpenDatastores)?;
    let catalog = Arc::new(PivotCatalog::new(
        datastores,
        metastore.default_datastore_name().to_string(),
    )?);
    // Start the datastore's background maintenance for the session, as the
    // server does when it begins serving.
    catalog.start();
    let session = session::Session::new(catalog.clone(), dispatcher);

    let interactive = std::io::stdin().is_terminal();
    if interactive {
        eprintln!("pivot-cli ({})", env!("CARGO_PKG_VERSION"));
    }
    eprintln!(
        "pivot session data: {}{}\npivot session config: {}",
        data_dir.display(),
        if args.path.is_none() {
            " (removed on exit)"
        } else {
            ""
        },
        config_path.display()
    );
    if interactive {
        eprintln!("Type \\h for help or \\q to quit.");
    }

    let mut shell = repl::Shell::new(&session, &mut sigint, &mut sigterm, &mut sighup);
    let reason = if interactive {
        shell.run_interactive().await?
    } else {
        let script =
            tokio::task::spawn_blocking(|| std::io::read_to_string(std::io::stdin())).await??;
        shell.run_script(&script).await
    };

    // Tear the engine down the way the server's shutdown path does: stop the
    // datastore's maintenance before the pool, flip the shared exit flag, and
    // wait for every worker to observe it. The wait is unbounded, so give
    // Ctrl-C its usual meaning back rather than hold the terminal hostage.
    catalog.abort();
    engine_shutdown.shutdown();
    let draining = tokio::task::spawn_blocking(move || {
        for handle in worker_handles {
            let _ = handle.join();
        }
    });
    tokio::select! {
        drained = draining => drained?,
        _ = sigint.recv() => {
            eprintln!("interrupted while stopping the engine; exiting without draining it");
        }
    }

    Ok(match reason {
        repl::ExitReason::Quit => ExitCode::SUCCESS,
        repl::ExitReason::Terminated => ExitCode::FAILURE,
    })
}

fn main() -> ExitCode {
    match run() {
        Ok(code) => code,
        Err(error) => {
            eprintln!("Error: {error}");
            ExitCode::FAILURE
        }
    }
}
